### ISSUE TITLE
A better way to call the api.

### ISSUE THREAD

**Issue by aaronbwcollins** [jamfit/Encrypted-Script-Parameters#1]
I found you can provide the hash, salt and passphrase without storing any info in the script.

`DecryptString () {
    echo "${1}" | /usr/bin/openssl enc -aes256 -d -a -A -S "${2}" -k "${3}"
}
apiPass=$(DecryptString $4 $5 $6)`

Let me know if you foresee any issues with this method.

**Comment by jamfit** [comment]
@aaronbwcollins By placing the encrypted string with the salt and passphrase as parameters in the policy anyone can obtain the account password if they view the policy data. By placing the salt and the passphrase into the script and keeping the string in the policy someone would need access to both pieces in order to obtain the password.

**Comment by aaronbwcollins** [comment]
@jamfit Besides the compromise of the JSS when can an attacker get ahold of the policy data?
